mysql:
  image: mysql:latest
  ports:
    - "3310:3306"
  environment:
    MYSQL_ROOT_PASSWORD: admin
    MYSQL_DATABASE: inmar

web:
  build: .
  command:
    - /bin/sh
    - -c
    - |
          python manage.py migrate
          python manage.py runserver 0.0.0.0:3001
          sleep 10
          http -f POST http://localhost:3001/api/v1/importdata file@Data.csv
  volumes:
    - .:/var
  ports:
    - "3001:3001"
  links:
    - mysql
